///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AndroidTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LoginModule recording.
    /// </summary>
    [TestModule("afc07735-f5b8-4fe6-8441-f1da6122ff81", ModuleType.Recording, 1)]
    public partial class LoginModule : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AndroidTestRepository repository.
        /// </summary>
        public static AndroidTestRepository repo = AndroidTestRepository.Instance;

        static LoginModule instance = new LoginModule();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LoginModule()
        {
            varMobileDevice = "Center";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LoginModule Instance
        {
            get { return instance; }
        }

#region Variables

        string _varMobileDevice;

        /// <summary>
        /// Gets or sets the value of variable varMobileDevice.
        /// </summary>
        [TestVariable("d4466bb4-281e-4fe1-999a-e83e511d1d3d")]
        public string varMobileDevice
        {
            get { return _varMobileDevice; }
            set { _varMobileDevice = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComVodafoneViewer.LoginActivity.Manage_Click' at Center", repo.ComVodafoneViewer.LoginActivity.Manage_ClickInfo, new RecordItemIndex(0));
            repo.ComVodafoneViewer.LoginActivity.Manage_Click.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComVodafoneViewer.LoginActivity.Edit_Click' at Center", repo.ComVodafoneViewer.LoginActivity.Edit_ClickInfo, new RecordItemIndex(1));
            repo.ComVodafoneViewer.LoginActivity.Edit_Click.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'Ramya' on item 'ComVodafoneViewer.Content.EnterUsername'.", repo.ComVodafoneViewer.Content.EnterUsernameInfo, new RecordItemIndex(2));
            repo.ComVodafoneViewer.Content.EnterUsername.Element.SetAttributeValue("Text", "Ramya");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'Hunsvi' on item 'ComVodafoneViewer.Content.EnterPassword'.", repo.ComVodafoneViewer.Content.EnterPasswordInfo, new RecordItemIndex(3));
            repo.ComVodafoneViewer.Content.EnterPassword.Element.SetAttributeValue("Text", "Hunsvi");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComVodafoneViewer.Content.Next_Click' at Center", repo.ComVodafoneViewer.Content.Next_ClickInfo, new RecordItemIndex(4));
            repo.ComVodafoneViewer.Content.Next_Click.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComVodafoneViewer.LoginActivity.Connect_Click' at Center", repo.ComVodafoneViewer.LoginActivity.Connect_ClickInfo, new RecordItemIndex(5));
            repo.ComVodafoneViewer.LoginActivity.Connect_Click.Touch();
            Delay.Milliseconds(300);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
